const questions = [
  {
    id: 'confirmation',
    type: 'confirmation',
    question: 'Would you like to continue with this onboarding process? This will require your University of Manitoba student email.',
    continueLabel: 'Continue',
    endLabel: 'End Onboarding',
    required: true,
    update: false,
  },
  {
    id: 'email',
    type: 'modal',
    question: 'What is your University of Manitoba student email address?',
    buttonLabel: 'Enter Email',
    modalTitle: 'University of Manitoba Email',
    modalLabel: 'Your UofM student email address:',
    placeholder: 'student@myumanitoba.ca',
    inputStyle: 'Short',
    required: true,
    update: true,
    verification: true,
  },
  {
    id: 'name',
    type: 'modal',
    question: 'What is your full name?',
    buttonLabel: 'Enter Full Name',
    modalTitle: 'Full Name',
    modalLabel: 'What is your full name?',
    placeholder: 'John Doe',
    inputStyle: 'Short',
    required: true,
    update: true,
  },
  {
    id: 'games',
    type: 'multiSelect',
    question: 'What game(s) would you watch or play? (Select all that apply)',
    placeholder: 'Select Games',
    options: [
      { label: 'Valorant', value: 'valorant' },
      { label: 'League Of Legends', value: 'league' },
      { label: 'CS2', value: 'cs2' },
      { label: 'Team Fortress 2', value: 'tf2' },
      { label: 'Overwatch', value: 'overwatch' },
      { label: 'Rocket League', value: 'rocket_league' },
      { label: 'Rainbow Six Siege', value: 'r6' },
      { label: 'Call Of Duty', value: 'cod' },
      { label: 'Fortnite', value: 'fortnite' },
      { label: 'Apex Legends', value: 'apex' },
      { label: 'Super Smash Bros', value: 'smash' },
    ],
    minValues: 0,
    maxValues: 11,
    required: false,
    update: false,
  },
  {
    id: 'other_games',
    type: 'modal',
    question: 'Any other games you\'re interested in that weren\'t listed above?',
    buttonLabel: 'Enter Other Games',
    modalTitle: 'Other Games',
    modalLabel: 'Other games (separate with semicolons):',
    placeholder: 'Minecraft; Terraria; Among Us',
    inputStyle: 'Short',
    required: false,
    update: true,
  },
  {
    id: 'participation',
    type: 'select',
    question: 'Would you be participating Recreationally or Competitively?',
    placeholder: 'Select Participation Type',
    options: [
      { label: 'Recreational', value: 'recreational' },
      { label: 'Competitive', value: 'competitive' },
    ],
    required: true,
    update: false,
  },
  {
    id: 'discord_features',
    type: 'modal',
    question: 'What features would you like to see us add on the discord? (respectful and SFW answers only)',
    buttonLabel: 'Suggest Discord Features',
    modalTitle: 'Discord Feature Suggestions',
    modalLabel: 'Discord feature suggestions:',
    placeholder: 'Your suggestions here...',
    inputStyle: 'Paragraph',
    required: false,
    update: false,
  },
  {
    id: 'incentives',
    type: 'modal',
    question: 'Are there specific incentives or rewards that would encourage your participation? (respectful and SFW answers only)',
    buttonLabel: 'Suggest Incentives',
    modalTitle: 'Participation Incentives',
    modalLabel: 'Participation incentives/rewards:',
    placeholder: 'Your ideas here...',
    inputStyle: 'Paragraph',
    required: false,
    update: false,
  },
  {
    id: 'non_gaming_events',
    type: 'modal',
    question: 'Any non-gaming events you would like us to host? (respectful and SFW answers only)',
    buttonLabel: 'Suggest Non-Gaming Events',
    modalTitle: 'Non-Gaming Event Ideas',
    modalLabel: 'Non-gaming event ideas:',
    placeholder: 'Your event ideas here...',
    inputStyle: 'Paragraph',
    required: false,
    update: false,
  },
  {
    id: 'exec_comments',
    type: 'modal',
    question: 'Questions or Comments for the Exec team? (respectful and SFW answers only)',
    buttonLabel: 'Leave Comments',
    modalTitle: 'Executive Team Comments',
    modalLabel: 'Questions/comments for exec team:',
    placeholder: 'Your questions or comments here...',
    inputStyle: 'Paragraph',
    required: false,
    update: false,
  },
]

module.exports = { questions }
